# Generated by Django 2.2 on 2019-04-29 09:54

from django.db import migrations
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='blog_tagline',
            new_name='courseCode',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='blog_name',
            new_name='courseName',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AddField(
            model_name='entry',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
